let text1 = "      Hello World!      ";
let text2 = text1.trim();
console.log(text2);
console.log(text2.length);
let text3 = "     Hello World!     ";
let text4 = text3.trimStart();
console.log(text4);
console.log(text4.length);
let text5 = "     Hello World!     ";
let text6 = text5.trimEnd();
console.log(text6);
console.log(text6.length);